package com.datarelay.core.config;

import java.time.Instant;
import java.util.UUID;

import org.bson.UuidRepresentation;
import org.springframework.boot.mongodb.autoconfigure.MongoClientSettingsBuilderCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.mongodb.core.mapping.event.ReactiveBeforeConvertCallback;

import com.datarelay.core.entity.DataStream;

import reactor.core.publisher.Mono;

@Configuration
public class MongoConfig {

    @Bean
    public MongoClientSettingsBuilderCustomizer mongoUuidCustomizer() {
        return builder -> builder.uuidRepresentation(UuidRepresentation.STANDARD);
    }
    
    @Bean
    public ReactiveBeforeConvertCallback<DataStream> autoGenerateDefaults() {
        return (entity, collection) -> {
            entity.setStreamId(UUID.randomUUID());
            entity.setTimestamp(Instant.now());
            
            return Mono.just(entity);
        };
    }
}
